apiVersion: v1
kind: Pod
metadata:
  name: secure-pod
  namespace: cka-koans
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  containers:
    - name: busybox
      image: busybox:1.36
      command: ["sleep", "3600"]
      securityContext:
        readOnlyRootFilesystem: true
