apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: CHANGE_ME
  namespace: cka-koans
spec:
  selector:
    matchLabels:
      app: CHANGE_ME
  template:
    metadata:
      labels:
        app: CHANGE_ME
    spec:
      containers:
        - name: agent
          image: busybox:1.36
          command: ["sleep", "3600"]
