apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: troubleshoot-adv
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-ssd
  resources:
    requests:
      storage: 1Gi
