apiVersion: v1
kind: Pod
metadata:
  name: toleration-demo
  namespace: cka-koans
spec:
  containers:
    - name: busybox
      image: busybox:1.36
      command: ["sleep", "3600"]
  tolerations:
    - key: dedicated
      operator: Equal
      value: training
      effect: NoSchedule
