apiVersion: v1
kind: Pod
metadata:
  name: affinity-demo
  namespace: cka-koans
spec:
  containers:
    - name: busybox
      image: busybox:1.36
      command: ["sleep", "3600"]
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: CHANGE_ME
                operator: In
                values:
                  - CHANGE_ME
