apiVersion: v1
kind: Pod
metadata:
  name: init-demo
  namespace: cka-koans
spec:
  initContainers:
    - name: init-setup
      image: busybox:1.36
      command: ["sh", "-c", "echo CHANGE_ME > /work/status.txt"]
      volumeMounts:
        - name: workdir
          mountPath: /work
  containers:
    - name: main
      image: busybox:1.36
      command: ["sleep", "3600"]
      volumeMounts:
        - name: workdir
          mountPath: /work
  volumes:
    - name: workdir
      emptyDir: {}
