apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: cka-koans
spec:
  serviceName: CHANGE_ME
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
