apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
  namespace: troubleshoot-adv
subjects:
  - kind: ServiceAccount
    name: rbac-sa
    namespace: troubleshoot-adv
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
