apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-cron
  namespace: cka-koans
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: busybox
              image: busybox:1.36
              command: ["echo", "hello"]
