apiVersion: batch/v1
kind: CronJob
metadata:
  name: CHANGE_ME
  namespace: cka-koans
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: busybox
              image: busybox:1.36
              command: ["echo", "CHANGE_ME"]
