apiVersion: v1
kind: Pod
metadata:
  name: hello-koans
  namespace: cka-koans
  labels:
    app: pod-basics
spec:
  restartPolicy: Always
  containers:
    - name: nginx
      image: nginx:1.25
      ports:
        - name: http
          containerPort: 80
